version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flaskapp
      - POSTGRES_PASSWORD=flaskapp
      - POSTGRES_DB=flaskapp_dev
    ports:
      - 5432:5432
  pgadmin4:
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - 5433:80
volumes:
  postgres_data:
